name: ci

on: push
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Baixar o repositório
              uses: actions/checkout@v4

            - name: Instalar o Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.13.7

            - name: Instalar o uv via pip
              run: pip install uv

            - name: Instalar dependências com o uv
              run: uv pip install -r requirements.txt

            - name: Rodar minha rotina de testes com o uv
              run: uv run pytest tests -v